'''
Author: ChatGPT, Wei Qin
Date: 2023-12-22
Description:
    Find duplicate files in two folders. Generated by ChatGPT and edited by me. 
Update Log:
    2023-12-22: File created.

'''

import hashlib
import os


def hash_file(file_path):
    """Compute SHA256 hash of a file."""
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def list_files(directory):
    """List all file paths in a directory."""
    return [os.path.join(directory, file) for file in os.listdir(directory) if os.path.isfile(os.path.join(directory, file))]


def find_duplicate_files(folder1, folder2):
    """Find duplicate files by content in two folders."""
    folder1_files = list_files(folder1)
    folder2_files = list_files(folder2)

    # Create a list of (hash, filepath) for each folder
    folder1_hashes = [(hash_file(file), file) for file in folder1_files]
    folder2_hashes = [(hash_file(file), file) for file in folder2_files]
    
    duplicates = []

    # Compare each file in folder1 against all files in folder2
    for hash1, file1 in folder1_hashes:
        for hash2, file2 in folder2_hashes:
            if hash1 == hash2:
                duplicates.append((file1, file2))

    return duplicates

# Usage
if __name__ == '__main__':
    folder1 = "/work/99_temp/duplicate_2"
    folder2 = "/work/99_temp/duplicate_1"
    duplicates = find_duplicate_files(folder1, folder2)
    
    print("Duplicate files: ")
    for file1, file2 in duplicates:
        print(f"{file1} and {file2}")
